FROM odoo:18.0

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends git \
    && rm -rf /var/lib/apt/lists/*

RUN git clone --depth 1 --branch 18.0 https://github.com/OCA/OpenUpgrade.git /opt/openupgrade \
    && pip3 install --break-system-packages --no-cache-dir git+https://github.com/OCA/openupgradelib.git@master#egg=openupgradelib

USER odoo
